version: "3"

services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes: 
            - ./django_reviews:/app
            - /tmp/${MYSQL_DATABASE}/mysqld:/var/run/mysqld
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
        depends_on: 
            - db

    db:
        image: mysql:5.7
        restart: always
        environment: 
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            # MYSQL_USER: 'root'
            MYSQL_PORT: '3306'
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - '3306:3306'