version: "3"

services:
    app:
        restart: always
        env_file: .env
        build:
            context: .
        ports:
            - "8000:8000"
        volumes: 
            - ./django_reviews:/app
            - reviews:/var/run/mysqld
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"
        depends_on: 
            - mysql

    mysql:
        env_file: .env
        image: mysql:5.7
        restart: always
        environment: 
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            # MYSQL_USER: 'root'
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - '${MYSQL_PORT}:${MYSQL_PORT}'

volumes: 
    reviews: