# Generated by Django 3.0.7 on 2020-08-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20200611_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
